branches:
  only:
    - develop
    - /^releases\/.*$/

jobs:
  fast_finish: true
  include:
    - stage: "style check"
      python: '3.7'
      os: linux
      language: python
      script:
        - black --diff --check .
        - flake8
        